# Generated by Django 3.2 on 2021-04-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_followmodel_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='followmodel',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_list', to='authentication.Profile'),
        ),
    ]
