# Generated by Django 3.2 on 2021-04-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.URLField(default='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.desicomments.com%2Fwp-content%2Fuploads%2F2017%2F02%2FAutumn-Image.jpg&f=1&nofb=1'),
        ),
    ]
