# Generated by Django 3.1.8 on 2021-04-19 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210419_1319'),
        ('index', '0004_auto_20210419_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_by', to='authentication.profile'),
        ),
    ]
