# Generated by Django 3.2 on 2021-04-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210419_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shared_post_url',
        ),
        migrations.AddField(
            model_name='post',
            name='shared_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
