# Generated by Django 3.2 on 2021-04-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210419_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
