# Generated by Django 3.2 on 2021-04-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_post_shared_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at']},
        ),
    ]
