# Generated by Django 3.2 on 2021-04-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_followmodel_followers'),
        ('index', '0012_alter_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_for_algo',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='ViewedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.post')),
            ],
        ),
    ]
