# Generated by Django 3.2 on 2021-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20210423_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views_for_algo',
            field=models.IntegerField(default=0),
        ),
    ]
