# Generated by Django 3.2 on 2021-04-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_alter_post_views_for_algo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
