# Generated by Django 3.1.8 on 2021-04-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_mostratedfortheweek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mostRatedForTheWeek',
        ),
    ]
