# Generated by Django 3.1.8 on 2021-04-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_delete_mostratedfortheweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='lastUpdated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='ranksReseted',
        ),
    ]
