# Generated by Django 3.1.8 on 2021-04-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20210426_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lastUpdated',
        ),
    ]
