# Generated by Django 3.1.8 on 2021-04-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20210426_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
